### ISSUE TITLE
EELS spectrum image isn't read correctly after rotating for correct dimension order

### ISSUE THREAD

**Issue by thomasaarholt** [niermann/gms_plugin_hdf5#3]
Trying to load in a spectrum, and rotating it to account for #2 does not let a spectrum be read when I try to use the spectrum picker tool (available with the EELS and EDS DM packages).

It would be very nice if this could be supported. Until then, it isn't really possible to use DM for analysing imported spectrum images.

![image](https://user-images.githubusercontent.com/2721423/27635830-f2428d54-5c08-11e7-9c55-a95d02003522.png)

**Comment by Bejoscha** [comment]
This is rather a DM tagging issue, I believe. The picker will only work if the data is properly tagged with the "Meta Data" tags matching. In particular, the "Signal" tag must match the signal licensed for the picker (EDS or EELS) - at least in GMS 2. GMS 3 does not need this anymore. The "Format" tag must be "Spectrum image".

![image](https://user-images.githubusercontent.com/6987920/27638277-f96c2162-5c12-11e7-85cc-7d148ebb0bf5.png)

I also belive that some older versions of GMS did not support the picker if the data isn't real-4 or real-8. 

Note, that editing the tags of an already shown image will not help. The tags must be there when the image gets first displayed. (You can add tags, save, and re-open.)

**Comment by niermann** [comment]
As I read @Bejoscha's answer this seems to be a DM issue. The plugin is intended to provide methods to read HDF5 files. This is not a plugin to import hyperspy datasets into DM. However, it can be used to import data from arbitrary HDF5 files into DM (without providing the necessary interpretations/metadata). If anyone writes a script dealing with the necessary DM peculiarities, I'm happy to include it into the repository (also see my comment in #2).

**Comment by thomasaarholt** [comment]
Just wanted to emphasise my appreciation of this package! I realise that I came across with a very hyperspy-angled approach, which I didn't mean to. It's just that this has been a major barrier for EM-research within the python community for a while - the fact that someone had written this plugin was a huge revelation! I'll try to find the time to contribute!

**Comment by niermann** [comment]
Thanks very much. Nice too hear that the plugin is useful for other people. Sorry, if I sounded a bit offended. I appreciate your intention and I am fully aware that without dedicated hyperspy support, the possibilities of the plugin are not fully leveraged. Also the plugin itself without UI or something like that is not very user-friendly. When you find time to create a DM script to provide features on top of the plugin, feel free to contact me for help.
