### ISSUE TITLE
Navigating multidimensional hdf5s (GMS3)

### ISSUE THREAD

**Issue by thomasaarholt** [niermann/gms_plugin_hdf5#4]
The following problem may have been introduced with GMS3, so I'm wondering if you have any suggestions:

The "slice" tool does not let me navigate hdf5 datasets loaded with this plugin.

I just tried loading in the [hyperslab.hdf5](https://github.com/niermann/gms_plugin_hdf5/blob/master/tests/hyperslab.hdf5) file found in the test folder on this repo. 

When I load it, the slice tool does not display any sliders at all. Do you know if this was the case in the DM2.3 version? 

![image](https://user-images.githubusercontent.com/2721423/41776214-2ddfbcae-7627-11e8-96b4-46b3b1fc5d40.png)
![image](https://user-images.githubusercontent.com/2721423/41776815-75879aac-7629-11e8-9ced-5f8383984558.png)

Edit: added visible pane showing that Control does not have any controls either.

**Comment by niermann** [comment]
I just checked with GMS 2.3. The slice tool seems not to work on 4D datasets. I tried it with the dataset loaded by the plugin, as well as datasets created by:
`ShowImage(IntegerImage("", 2, 0, 16, 16, 16, 16))` in  the DM script window. 

I assume the slice-tool will work only on 3D datasets. The support for 4D datasets in DM is very limited to my knowledge. This seems to be a general DM issue, not specific to the plugin.

**Comment by thomasaarholt** [comment]
Thanks for the clarification! 
I guess I'll have to stick to 3D file for now.

**Comment by thomasaarholt** [comment]
In case anyone else wonders: You can in fact use the arrow keys to navigate one of the dimensions in the 4D image, but you won't be able to see which index you are at, nor be able to navigate the other dimension.

**Comment by Bejoscha** [comment]
Hi all,
For clarification: The slice tool works just fine with 4D data in both GMS 2 and GMS 3 (and actually GMS 1), but it is a licensed product! 
You need to have the STEM DI license for it, or the feature is not available.
Similar (but somewhat relaxed) situation for 3D data and the "picker" tool:  This is a licensed feature (SpectrumImaging) as well.
However, in GMS 3 you can get the "SI Viewer" license for free, which enables the picker tool for 3D  (but not 4D and 5D).

Regardless of the licencing situation, data can be accessed in all dimensions by scripting of course. I would advise using the SliceN() command.


-----Original Message-----

**Comment by w4m0330** [comment]
In my case, the 4D data worked very nicely... Slice tools works, and the picker tools also. 
I first exported and saved the 2D frames in TIF series from the raw experiment data and then read in frame by frame and constructed a 4D hypercube.
![4d](https://user-images.githubusercontent.com/13786031/41780484-1d39ac4e-7635-11e8-8f4a-b6d41ea2b9ed.PNG)

**Comment by w4m0330** [comment]
This also works
ShowImage(IntegerImage("", 2, 0, 16, 16, 16, 16))
![capture](https://user-images.githubusercontent.com/13786031/41780649-a2c9a74c-7635-11e8-80b8-e0ae2bda69e4.PNG)

But, 5D dataset shows no slice tool and picker tool
ShowImage(IntegerImage("", 2, 0, 16, 16, 16, 16, 16))

**Comment by thomasaarholt** [comment]
@w4m0330 I suspect then that you have the STEM DI package that @Bejoscha spoke of in his reply.

**Comment by Bejoscha** [comment]
For GMS 3.2.2 (the latest), the (free) SI Viewer license is seemingly enough.
See https://stackoverflow.com/a/50989996/1302888 

5D has never been supported by a slice tool (also, what would the "3D" display be that it refers to?).
I don't think 5D data is used particularly often anywhere yet... A time series of STEM DI data possibly... 

-----Original Message-----

**Comment by thomasaarholt** [comment]
@Bejoscha I just sent a support request to Gatan since I can't get the SI Viewer installed in my GMS 3 version. Any chance you could help me work out what I'm doing wrong?
I currently have installed GMS 3 with EELS and spectrum imaging plugins. I then run the license installer for the SI Viewer, which successfully installs. Then I run the GMS installer, but there I only see available the options that I had previously:
![image](https://user-images.githubusercontent.com/2721423/47796411-96997280-dd24-11e8-9e87-1532b88310f8.png)

Additionally, I checked the C:\Users\thomasaar\AppData\Local\Temp\_GatanInstall folder, and found the licenses where I think they should be.

![image](https://user-images.githubusercontent.com/2721423/47796568-e5dfa300-dd24-11e8-862a-10e7a315938e.png)

Thoughts?

**Comment by Bejoscha** [comment]
Hi Thomas,
The SI Viewer (and other free licenses) are not compatible with other licenses you may have already installed.
This is, because these free licenses run under the site-ID "GATAN_FREE" whereas all purchased licenses will have the site-ID of the purchase.
However, if you already have GMS 3 with EELS and SI support, there really should be no need for you to install the SI Viewer, should there?
What functionality are you hoping to gain?

If you want to install the SI Viewer "free license", the best is to do a vanilla install, i.e. uninstall your current GMS 3 - and also remove the liceneses when asked. 
Then install the SI Viewer license with the License installer and then the GMS 3 regular installer.

Hope this helps, otherwise just ask again,
  B


-----Original Message-----

**Comment by thomasaarholt** [comment]
Ah, I just realised that I wouldn't have gotten the functionality I wanted anyway.

In short, I didn't re-read your previous post about how one needed the licensed STEM DI plugin to navigate 4D datasets! So my bad!
