### ISSUE TITLE
Meta data not imported into DM

### ISSUE THREAD

**Issue by michaelwuww** [niermann/gms_plugin_hdf5#5]
Hi all,

Using the 1.2v of the plug-in, I imported an EELS spectrum mapping file, but it is missing the calibrations.
![image](https://user-images.githubusercontent.com/108194693/179602444-9ccdc089-ccbc-482a-9fb8-3d3b6e4da66b.png)
As far as I can tell, it's in this part of the DM script that gets the "tags" for calibration.
![image](https://user-images.githubusercontent.com/108194693/179601736-511307b4-d568-495c-9eb3-e157f02540d4.png)
I have tried changing the variable names, but nothing seems to change.
![image](https://user-images.githubusercontent.com/108194693/179601026-a9263e44-1a16-4f2d-b4be-e51cc26f2a42.png)
Any suggestion will be appreciated!

**Comment by niermann** [comment]
Hi,

probably the EELS mapping doesn't have the metadata in the format expected by the example script. 

Actually HDF5 files are just container files (like a zip file is a container file for other files). However, the HDF5 file itself has no standard way how metadata like calibrations is actually stored in the file. It only provides ways to store (meta) data but gives no higher level semantic to the stored data. This semantic is provided by higher level standards based on HDF5 (e.g. CDF, Velox Files, Hyperspy-Files, TemDataFile etc). However, all these standards save the metadata differently. 

The HDF5 plugin itself provides ways to read data stored in HDF5 files. It does not assumes any higher level standard, nor it parses any meta data at all. The provided DM script gives an example how to implement higher level parsers. The DM script itself parses metadata, which is stored in the way as done by my [holoaverage](https://github.com/niermann/holoaverage) package. The source of your EELS mapping will most surely store it differently. So you have to adopt the import script to your file standard.

**Comment by michaelwuww** [comment]
Hi Niermann,

Thank you for your helpful response! I looked into the holoaverage package and had a few questions. 
I found that you stored these values like such in average.py.
![image](https://user-images.githubusercontent.com/108194693/179936411-1714e262-4786-446a-a863-9c72cb42a4d3.png)
data.attrs["name of the item"]
In hyperspy, the calibrations can be called from data.axes_manager[0].scale.
In this case, would h5_read_attr(filename, name) still be able to find the calibrations in the hyperspy standard?
I was able to find this function in h5_attr.cpp, but have some trouble understanding how it works.
![image](https://user-images.githubusercontent.com/108194693/179942211-099d4abc-539b-4672-80a8-588de56d6910.png)

**Comment by niermann** [comment]
I actually don't know, how exactly hyperspy saves its data (never found the time to use it on my data). This perhaps is more a questions for the guys at hyperspy. It might be that they already have a script to import hyperspy files into DM. Without knowing the structure they use in their files, I only can give some general hints:

A DM script with something like: `TagGroup attr = h5_read_attr(filename, name_of_dataset_in_file)` with the right name of the file and name of the dataset should give you all attributes of the dataset. You than can use DM's methods like `TagGroupGetTagAsNumber` to query the attributes.

If you want to get more insight into the actual HDF5 file structure you also can use the [hdfview](https://www.hdfgroup.org/downloads/hdfview/) program to view the HDF5 files.

**Comment by michaelwuww** [comment]
Hi Niermann,

Thank you so much for your help again!
I was able to get it to work although it might have a lot of bugs.
![image](https://user-images.githubusercontent.com/108194693/180076036-2d05fbff-31f5-49e3-9562-7e5b8e4ca6e8.png)
Using the hdfview program, I was able to see how hyperspy structures its data.
![image](https://user-images.githubusercontent.com/108194693/180066423-e1ea0e4f-25ae-47eb-880f-b45f0f85a901.png)
The calibrations I need are in axis-0.

Here is a summary of what I did:
![image](https://user-images.githubusercontent.com/108194693/180076195-aa7b5148-3764-4c10-9df0-bf92d67dae97.png)
The name that is used for H5IMPORT_import_single(filename, name, 0) is pointing to /Experiments/__unnamed__/data, but the calibrations for the axis are stored in axis-0,1,2.
I could not figure out an easy way to manipulate String with DM script so I fixed the location where attributes are being read
from h5_read_attr(filename, name) to h5_read_attr(filename, "/Experiments/__unnamed__/axis-0").
![image](https://user-images.githubusercontent.com/108194693/180077404-c79de256-e830-4b42-a31e-75468104a650.png)
Finally changed the text to match the hyperspy format and set these values to the interested dimension.
![image](https://user-images.githubusercontent.com/108194693/180077951-470ff2d3-96c3-4415-ae16-3697080b4a0c.png)

**Comment by niermann** [comment]
Hi Michael,

it seems you managed successfully to read the metadata information. It is some days (actually years) ago, I fiddled around with DM scripting, so I have forgotten how to do the string parsing in DM itself. 

Just one thing, which comes into my mind: The example DM script in the repository looks for all array-like datasets in the HDF5 file and calls H5IMPORT_import_single directly with the name of a dataset, if there is only one. Otherwise, a dialog is displayed querying the user which dataset to import and then calls H5IMPORT_import_single for this dataset. For Hyperspy files this might be not the most robust way to do so, since hyperspy might save other metadata as array-like datasets in the HDF5 file.

**Comment by michaelwuww** [comment]
I see. So far all my data has only one dataset. Maybe I will tackle the issue you mentioned later when the time comes lol. Thanks for the help again!
